### ISSUE TITLE
Client compilation failure when including boost/network/protocol/http/server.hpp

### ISSUE THREAD

**Issue by glynos** [cpp-netlib/cpp-netlib#13]
The following code fails to compile on MSVC 8.0:

```
#include "boost/network/protocol/http/client.hpp"
#include "boost/network/protocol/http/server.hpp"
int
main(int argc, char *argv[]) {
    typedef
        boost::network::http::basic_client<boost::network::tags::http_keepalive_8bit_udp_resolve, 1, 1> http_client;
    http_client client;
    return 0;
}
```

This fails with the following compilation error:

```
..\..\..\boost/network/protocol/http/policies/sync_resolver.hpp(25) : error C2059: syntax error : '<'
        ..\..\..\boost/network/protocol/http/policies/pooled_connection.hpp(25) : see reference to class template instantiation 'boost::network::http::policies::sync_resolver<Tag>' being compiled
        with
        [
            Tag=boost::network::tags::http_keepalive_8bit_udp_resolve
        ]
        ..\..\..\boost/network/protocol/http/client.hpp(29) : see reference to class template instantiation 'boost::network::http::pooled_connection_policy<Tag,version_major,version_minor>' being compiled
        with
        [
            Tag=boost::network::tags::http_keepalive_8bit_udp_resolve,
            version_major=1,
            version_minor=1
        ]
        erik_test.cpp(16) : see reference to class template instantiation 'boost::network::http::basic_client<Tag,version_major,version_minor>' being compiled
        with
        [
            Tag=boost::network::tags::http_keepalive_8bit_udp_resolve,
            version_major=1,
            version_minor=1
        ]
..\..\..\boost/network/protocol/http/policies/sync_resolver.hpp(25) : error C2039: 'type' : is not a member of '`global namespace''
..\..\..\boost/network/protocol/http/policies/sync_resolver.hpp(25) : error C2238: unexpected token(s) preceding ';'
..\..\..\boost/network/protocol/http/policies/sync_resolver.hpp(26) : error C2065: 'string_type' : undeclared identifier
..\..\..\boost/network/protocol/http/policies/sync_resolver.hpp(32) : error C2061: syntax error : identifier 'string_type'
```
