### ISSUE TITLE
issue compiling on OSX

### ISSUE THREAD

**Issue by mclark4386** [cpp-netlib/cpp-netlib#134]
First I have boost 1.50 installed via macports on Mountain Lion.

When I try to compile with clang 3.1(latest xcode) I get this on make (using master and any other branch I've tried):

<pre><code>[ 45%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-http-server.dir/http/server_sync_impl.cpp.o
cd /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src && /usr/bin/clang++   -DBOOST_NETWORK_ENABLE_HTTPS -I/opt/local/include -I/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/include -I/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib    -o CMakeFiles/cppnetlib-http-server.dir/http/server_sync_impl.cpp.o -c /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src/http/server_sync_impl.cpp
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src/http/server_sync_impl.cpp:7:
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/sync_impl.ipp:11:
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:196:30: error: 
      expected expression
                             [](buffer_type const &buffer) {
                             ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:285:10: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto const &header : headers) {
         ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:285:29: warning: 
      range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (auto const &header : headers) {
                            ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:294:26: error: 
      expected expression
      response_.get_body([&done, &buffer](iterator_range<char const *> data) {
                         ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:298:34: error: 
      no member named 'emplace_back' in 'std::list<boost::array<char, 4096>, std::allocator<boost::array<char,
      4096>>>'
      if (!done) output_buffers_.emplace_back(std::move(buffer));
                 ~~~~~~~~~~~~~~~ ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:298:52: error: 
      no member named 'move' in namespace 'std'; did you mean 'move'?
      if (!done) output_buffers_.emplace_back(std::move(buffer));
                                              ~~~~~^~~~
                                                   move
/opt/local/include/boost/move/move.hpp:324:97: note: 'move' declared here
   inline typename BOOST_MOVE_BOOST_NS::disable_if<has_move_emulation_enabled_aux<T>, T&>::type move(T& x)
                                                                                                ^
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src/http/server_sync_impl.cpp:7:
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/sync_impl.ipp:11:
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:305:7: warning: 
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
      auto end = std::copy_n(boost::begin(data), buffer.size(), buffer.begin());
      ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:305:23: error: 
      no member named 'copy_n' in namespace 'std'; did you mean 'copy'?
      auto end = std::copy_n(boost::begin(data), buffer.size(), buffer.begin());
                 ~~~~~^~~~~~
                      copy
/usr/include/c++/4.2.1/bits/stl_algobase.h:389:5: note: 'copy' declared here
    copy(_InputIterator __first, _InputIterator __last,
    ^
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src/http/server_sync_impl.cpp:7:
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/sync_impl.ipp:11:
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:305:18: error: 
      no matching function for call to 'copy'
      auto end = std::copy_n(boost::begin(data), buffer.size(), buffer.begin());
                 ^~~~~~~~~~~
/usr/include/c++/4.2.1/bits/stl_algobase.h:389:5: note: candidate template ignored: deduced conflicting types
      for parameter '_InputIterator' ('__gnu_cxx::__normal_iterator<char *, std::basic_string<char>>' vs.
      'unsigned long')
    copy(_InputIterator __first, _InputIterator __last,
    ^
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/src/http/server_sync_impl.cpp:7:
In file included from /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/sync_impl.ipp:11:
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:307:23: error: 
      no member named 'emplace_back' in 'std::list<boost::array<char, 4096>, std::allocator<boost::array<char,
      4096>>>'
      output_buffers_.emplace_back(std::move(buffer));
      ~~~~~~~~~~~~~~~ ^
/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/boost/network/protocol/http/server/connection/sync.hpp:307:41: error: 
      no member named 'move' in namespace 'std'; did you mean 'move'?
      output_buffers_.emplace_back(std::move(buffer));
                                   ~~~~~^~~~
                                        move
/opt/local/include/boost/move/move.hpp:324:97: note: 'move' declared here
   inline typename BOOST_MOVE_BOOST_NS::disable_if<has_move_emulation_enabled_aux<T>, T&>::type move(T& x)
                                                                                                ^
3 warnings and 8 errors generated.
make[2]: *** [libs/network/src/CMakeFiles/cppnetlib-http-server.dir/http/server_sync_impl.cpp.o] Error 1
make[1]: *** [libs/network/src/CMakeFiles/cppnetlib-http-server.dir/all] Error 2
make: *** [all] Error 2</code></pre>


when I try to use g++ 4.7.1 this is what I get from make:

<pre><code>[ 58%] Building CXX object libs/network/test/uri/CMakeFiles/cpp-netlib-uri_builder_test.dir/uri_builder_test.cpp.o
cd /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/test/uri && /Users/mclark4386/bin/gcc-4.7.1/bin/g++-4.7   -DBOOST_NETWORK_ENABLE_HTTPS -I/opt/local/include -I/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib -I/Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/include    -Wall -o CMakeFiles/cpp-netlib-uri_builder_test.dir/uri_builder_test.cpp.o -c /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/test/uri/uri_builder_test.cpp
Linking CXX executable ../../../../tests/cpp-netlib-uri_builder_test
cd /Users/mclark4386/Projects/TESTS/Boost/cpp-netlib/cpp-netlib/libs/network/test/uri && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/cpp-netlib-uri_builder_test.dir/link.txt --verbose=1
/Users/mclark4386/bin/gcc-4.7.1/bin/g++-4.7    -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cpp-netlib-uri_builder_test.dir/uri_builder_test.cpp.o  -o ../../../../tests/cpp-netlib-uri_builder_test  /opt/local/lib/libboost_unit_test_framework-mt.a /opt/local/lib/libboost_system-mt.a /opt/local/lib/libboost_regex-mt.a /opt/local/lib/libboost_date_time-mt.a /opt/local/lib/libboost_thread-mt.a /opt/local/lib/libboost_filesystem-mt.a /opt/local/lib/libboost_program_options-mt.a ../../src/libcppnetlib-uri.a /opt/local/lib/libssl.dylib /opt/local/lib/libcrypto.dylib 
Undefined symbols for architecture x86_64:
  "icu_48::Locale::Locale(icu_48::Locale const&)", referenced from:
      boost::basic_regex<int, boost::icu_regex_traits>::imbue(icu_48::Locale) in libboost_regex-mt.a(icu.o)
      boost::re_detail::icu_regex_traits_implementation::icu_regex_traits_implementation(icu_48::Locale const&) in libboost_regex-mt.a(icu.o)
      boost::icu_regex_traits::imbue(icu_48::Locale)      in libboost_regex-mt.a(icu.o)
  "icu_48::Locale::Locale()", referenced from:
      boost::icu_regex_traits::icu_regex_traits() in libboost_regex-mt.a(icu.o)
  "icu_48::Locale::~Locale()", referenced from:
      boost::basic_regex<int, boost::icu_regex_traits>::imbue(icu_48::Locale) in libboost_regex-mt.a(icu.o)
      boost::re_detail::icu_regex_traits_implementation::~icu_regex_traits_implementation() in libboost_regex-mt.a(icu.o)
      boost::re_detail::icu_regex_traits_implementation::icu_regex_traits_implementation(icu_48::Locale const&) in libboost_regex-mt.a(icu.o)
      boost::icu_regex_traits::icu_regex_traits() in libboost_regex-mt.a(icu.o)
      boost::icu_regex_traits::imbue(icu_48::Locale)      in libboost_regex-mt.a(icu.o)
  "icu_48::Collator::createInstance(icu_48::Locale const&, UErrorCode&)", referenced from:
      boost::re_detail::icu_regex_traits_implementation::icu_regex_traits_implementation(icu_48::Locale const&) in libboost_regex-mt.a(icu.o)
  "_u_charFromName_48", referenced from:
      boost::icu_regex_traits::lookup_collatename(int const*, int const*) const in libboost_regex-mt.a(icu.o)
  "_u_charType_48", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_digit_48", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
      boost::re_detail::basic_regex_parser<int, boost::icu_regex_traits>::parse_perl_extension() in libboost_regex-mt.a(icu.o)
      boost::re_detail::basic_regex_parser<int, boost::icu_regex_traits>::parse_repeat_range(bool) in libboost_regex-mt.a(icu.o)
      boost::re_detail::basic_regex_parser<int, boost::icu_regex_traits>::unescape_character() in libboost_regex-mt.a(icu.o)
      boost::re_detail::basic_regex_parser<int, boost::icu_regex_traits>::parse_backref() in libboost_regex-mt.a(icu.o)
      boost::re_detail::basic_regex_parser<int, boost::icu_regex_traits>::parse_extended_escape() in libboost_regex-mt.a(icu.o)
  "_u_isblank_48", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_isspace_48", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
      boost::icu_regex_traits::lookup_classname(int const*, int const*) const in libboost_regex-mt.a(icu.o)
  "_u_tolower_48", referenced from:
      boost::icu_regex_traits::lookup_classname(int const*, int const*) const in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::unwind_char_repeat(bool) in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::unwind_short_set_repeat(bool) in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::match_soft_buffer_end() in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::match_set() in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::match_literal() in libboost_regex-mt.a(icu.o)
      boost::re_detail::perl_matcher<int const*, std::allocator<boost::sub_match<int const*> >, boost::icu_regex_traits>::match_combining() in libboost_regex-mt.a(icu.o)
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [tests/cpp-netlib-uri_builder_test] Error 1
make[1]: *** [libs/network/test/uri/CMakeFiles/cpp-netlib-uri_builder_test.dir/all] Error 2
make: *** [all] Error 2</code></pre>


Any ideas?
