### ISSUE TITLE
Does not compile with Boost 1.70 and newer

### ISSUE THREAD

**Issue by vitakot** [cpp-netlib/cpp-netlib#875]
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html

Removed the deprecated member functions named io_service(). The get_io_service() member functions should be used instead.

**Comment by MichaelWittgreffe** [comment]
Hi, is anyone able to provide feedback on this issue? I'm also unable to get the latest pull from github to compile with Boost 1_70_1, quoting not being able to find asio/tcp.hpp from boost/network/protocol/http/client/connection/normal_delegate.ipp:12:10.

**Comment by enricodetoma** [comment]
I made pull request #878 to address this problem

**Comment by oddvardm** [comment]
This library is seriously broken. I have now tried to use it with windows 10 and it is so screwed up it will not compile at all. Have spent 4 days going through CMake & diffrent versions of Boost & finaly gave up. I know that this is volunteer work, but it was reported almost 4 mounth ago. Please fix it or update document page with a installation procedure that works with Visual Studio & CMake.

**Comment by enricodetoma** [comment]
I use branch 0.13-release with Boost 1.70, Visual Studio 2017, cmake 3.15.1 and it's not broken at all.

**Comment by oddvardm** [comment]
Hi, 

I use cmake-3.15.4, boost 1.71.0 (tried all down to 1.65.0) and Visual Studio 2017. Running these steps: 


    1. mkdir build 
    2. cd build 
    3. cmake -DBOOST_ROOT=C:\Microsoft\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\Microsoft\boost_1_71_0\stage\lib .. ;build ok and a sln file is generated 
    4. start VS 2017 
    5. execute build ; fails on http_client ; can not find cxxopts.hpp 
    6. create cxxopts.hpp from git 
    7. build failes on count not defined in cxxopts::Options & a operator for source not supported 
    8. removed http_client project from solution 
    9. build ok 

Seems to be the cxxopts.hpp not up to speed or http_client.cpp not up to speed. This is how my status are right now. Gonna test the library to see if it works. 

Oddvard 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 10. oktober 2019 18:30:53 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I use branch 0.13-release with Boost 1.70, Visual Studio 2017, cmake 3.15.1 and it's not broken at all.

**Comment by enricodetoma** [comment]
cxxopts is a dependancy.
Did you tell git to pull the dependancies too?

Also, did you try with branch 0.13-release instead of master?
In the past I had problems with master (don't remember exactly, it was quite some time ago), so I used originally branch 0.12-release and now 0.13-release

**Comment by oddvardm** [comment]
Forgot this, 

To get the dependencies I executet: git submodules init & git submodules update. Not working. Else I had an issue with CMake find_package(Boost 1.71.0 blah blah) that had to be all lowercase -> boost to work 

Oddvard 


----- Opprinnelig melding -----

Fra: oddvardm@getmail.no 
Til: "cpp-netlib/cpp-netlib" <reply@reply.github.com> 
Sendt: 10. oktober 2019 19:01:23 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 

Hi, 

I use cmake-3.15.4, boost 1.71.0 (tried all down to 1.65.0) and Visual Studio 2017. Running these steps: 


    1. mkdir build 
    2. cd build 
    3. cmake -DBOOST_ROOT=C:\Microsoft\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\Microsoft\boost_1_71_0\stage\lib .. ;build ok and a sln file is generated 
    4. start VS 2017 
    5. execute build ; fails on http_client ; can not find cxxopts.hpp 
    6. create cxxopts.hpp from git 
    7. build failes on count not defined in cxxopts::Options & a operator for source not supported 
    8. removed http_client project from solution 
    9. build ok 

Seems to be the cxxopts.hpp not up to speed or http_client.cpp not up to speed. This is how my status are right now. Gonna test the library to see if it works. 

Oddvard 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 10. oktober 2019 18:30:53 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I use branch 0.13-release with Boost 1.70, Visual Studio 2017, cmake 3.15.1 and it's not broken at all.

**Comment by enricodetoma** [comment]
I see that I'm not building examples nor tests.
Probably some months ago I had problems with them, so I disabled them in CMake-gui.
The library itself works correctly with http(s) (I only need http(s) in my project).

**Comment by oddvardm** [comment]
Yup. I on the other hand, need the examples and the dependencies. Learning how to use it you see. 


----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 10. oktober 2019 19:19:04 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I see that I'm not building examples nor tests. 
Probably some months ago I had problems with them, so I disabled them in CMake-gui. 
The library itself works correctly with http(s) (I only need http(s) in my project).

**Comment by oddvardm** [comment]
Quick question. 

I want to build the cpp-netlib with openssl. I install precompiled libraries but CMake find_package seems not to accept them. Line 75 in CMakeLists.txt is where I tried to modify find_package(OpenSSL). The installation have bee modified with OPENSSL_ROOT_DIR environment variable but still no go. Is there any requirements for a special configuration file(s) in the OpenSSL directory? Her is a list of what is in it: 

OpenSSL-Win64 

10.10.2019 17.20 <DIR> . 
10.10.2019 17.20 <DIR> .. 
11.09.2019 07.07 89 acknowledgements.txt 
11.09.2019 07.07 383 authors.txt 
10.10.2019 17.20 <DIR> bin 
11.09.2019 07.07 570 357 changes.txt 
11.09.2019 07.07 6 408 c_rehash.pl 
11.09.2019 07.07 86 faq.txt 
11.09.2019 07.07 2 917 376 libcrypto-1_1-x64.dll 
11.09.2019 07.07 481 280 libssl-1_1-x64.dll 
11.09.2019 07.07 6 253 license.txt 
11.09.2019 07.07 39 820 news.txt 
11.09.2019 07.07 3 304 readme.txt 
10.10.2019 17.20 11 575 unins000.dat 
10.10.2019 17.19 730 789 unins000.exe 
12 File(s) 4 767 720 bytes 
3 Dir(s) 297 652 375 552 bytes free 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 10. oktober 2019 19:19:04 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I see that I'm not building examples nor tests. 
Probably some months ago I had problems with them, so I disabled them in CMake-gui. 
The library itself works correctly with http(s) (I only need http(s) in my project).

**Comment by oddvardm** [comment]
Hi, 

I messed up. Yesterday I told you that I was using Boost 1.71.0. That was wrong. I used 1.65.0. It is broken when I use 1.71.0. 

Severity Code Description Project File Line Suppression State 
Error C2039 'get_io_service': is not a member of 'boost::asio::ip::basic_resolver<boost::asio::ip::udp,boost::asio::executor>' hello_world_client C:\Microsoft\LibsForAirsimApp\cpp-netlib-0.13.0-final\boost\network\protocol\http\client\connection\async_base.hpp 62 

and other stuff to. All noted in the git comments. When I create my repository I clone https://github.com/cpp-netlib/cpp-netlib 

Still had to delete http_client project from solution. 

O. 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 10. oktober 2019 19:19:04 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I see that I'm not building examples nor tests. 
Probably some months ago I had problems with them, so I disabled them in CMake-gui. 
The library itself works correctly with http(s) (I only need http(s) in my project).

**Comment by enricodetoma** [comment]
About OpenSSL: using CMake-gui I put both OPEN_SSL_INCLUDE_DIR and SSL_EAY_RELEASE (full path to libssl.lib) and it finds it correctly

About boost 1.71: please pull latest branch `0.13-release`, not `master`. I submitted a patch to make it work with boost >= 1.70 (where get_io_service was removed). I see that the patch has not been merged in master yet.

**Comment by oddvardm** [comment]
Gonna try it. BIG 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 07:26:19 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



About OpenSSL: using CMake-gui I put both OPEN_SSL_INCLUDE_DIR and SSL_EAY_RELEASE (full path to libssl.lib) and it finds it correctly 

About boost 1.71: please pull latest branch 0.13-release , not master . I submitted a patch to make it work with boost >= 1.70 (where get_io_service was removed). I see that the patch has not been merged in master yet.

**Comment by oddvardm** [comment]
Need some clean up. 

First run resulted in error: 

C:\Microsoft\LibsForAirsimApp\cpp-netlib-cpp-netlib-0.13.0-final\build>cmake -DBOOST_ROOT=C:\Microsoft\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\Microsoft\boost_1_71_0\stage\lib .. 
-- Building for: Visual Studio 15 2017 
-- The C compiler identification is MSVC 19.16.27034.0 
-- The CXX compiler identification is MSVC 19.16.27034.0 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works 
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done 
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe 
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Detecting CXX compile features 
-- Detecting CXX compile features - done 
-- Looking for pthread.h 
-- Looking for pthread.h - not found 
-- Found Threads: TRUE 
CMake Error at C:/Microsoft/cmake-3.15.4-win64-x64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message): 
Could NOT find Boost (missing: system thread) (found suitable version 
"1.71.0", minimum required is "1.58.0") 
Call Stack (most recent call first): 
C:/Microsoft/cmake-3.15.4-win64-x64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE) 
C:/Microsoft/cmake-3.15.4-win64-x64/share/cmake-3.15/Modules/FindBoost.cmake:2161 (find_package_handle_standard_args) 
CMakeLists.txt:53 (find_package) 


-- Configuring incomplete, errors occurred! 
See also "C:/Microsoft/LibsForAirsimApp/cpp-netlib-cpp-netlib-0.13.0-final/build/CMakeFiles/CMakeOutput.log". 
See also "C:/Microsoft/LibsForAirsimApp/cpp-netlib-cpp-netlib-0.13.0-final/build/CMakeFiles/CMakeError.log". 

This error is fixed by edit CMakeLists.txt line 53 changing Boost to boost (this is a weired error). Possibly caused by boost config file. This should be noted somewhere in doc. 

second run; 

C:\Microsoft\LibsForAirsimApp\cpp-netlib-cpp-netlib-0.13.0-final\build>cmake -DBOOST_ROOT=C:\Microsoft\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\Microsoft\boost_1_71_0\stage\lib .. 
-- Building for: Visual Studio 15 2017 
-- The C compiler identification is MSVC 19.16.27034.0 
-- The CXX compiler identification is MSVC 19.16.27034.0 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works 
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done 
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe 
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Detecting CXX compile features 
-- Detecting CXX compile features - done 
-- Found Boost: C:/Microsoft/boost_1_71_0 (found version "1.71.0") 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
-- Looking for pthread.h 
-- Looking for pthread.h - not found 
-- Found Threads: TRUE 
CMake Error at CMakeLists.txt:128 (add_subdirectory): 
The source directory 

C:/Microsoft/LibsForAirsimApp/cpp-netlib-cpp-netlib-0.13.0-final/deps/googletest 

does not contain a CMakeLists.txt file. 


-- Configuring incomplete, errors occurred! 
See also "C:/Microsoft/LibsForAirsimApp/cpp-netlib-cpp-netlib-0.13.0-final/build/CMakeFiles/CMakeOutput.log". 
See also "C:/Microsoft/LibsForAirsimApp/cpp-netlib-cpp-netlib-0.13.0-final/build/CMakeFiles/CMakeError.log". 

caused by dependency problem. Git gave me an error when I tried to clone the release version so I had to download the zip and in that zip no dependencies where found. 

fixed by switching tests OFF 

then the same error as before. Can you provide the link that I have to clone or download zip from? 

O. 

----- Opprinnelig melding -----

Fra: oddvardm@getmail.no 
Til: "cpp-netlib/cpp-netlib" <reply@reply.github.com> 
Sendt: 11. oktober 2019 10:22:54 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 

Gonna try it. BIG 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 07:26:19 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



About OpenSSL: using CMake-gui I put both OPEN_SSL_INCLUDE_DIR and SSL_EAY_RELEASE (full path to libssl.lib) and it finds it correctly 

About boost 1.71: please pull latest branch 0.13-release , not master . I submitted a patch to make it work with boost >= 1.70 (where get_io_service was removed). I see that the patch has not been merged in master yet.

**Comment by enricodetoma** [comment]
Clone from standard link, then switch locally to 0.13-release branch. Don't download the zip, or you won't have the dependancies.

**Comment by enricodetoma** [comment]
Source directory is where you cloned the project. For build directory I usually put {source dir}/build but it's your choice.

**Comment by oddvardm** [comment]
This is very strange. 

I select the 0.13-release branch and try to clone it. I copy the URL and try to clone it in GITDesktop. What happens is that GIT askes me to log in (I allready In. I can clone other repositories and create issues fine). When I enter my login and password it starts for 1 second and then pop up the dialog again. Strange. I abandon GITDesktop.exe 

Still in browser https://github.com/cpp-netlib/cpp-netlib/tree/0.13-release (bransh selected button left) I press 'clone or download' button. Dowload via GITDesktop.exe just fine, but the clone is an old master. 

This was a no go. 

O. 

----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 11:40:04 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



Source directory is where you cloned the project. For build directory I usually put {source dir}/build but it's your choice.

**Comment by oddvardm** [comment]
Aboned this library. Used UK based Restbed solution. Thank you for your efforts. 

Oddvard 


----- Opprinnelig melding -----

Fra: "enricodetoma" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 11:40:04 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



Source directory is where you cloned the project. For build directory I usually put {source dir}/build but it's your choice.

**Comment by oddvardm** [comment]
Thanks man. I will have a look at it. You in Europe? 


----- Opprinnelig melding -----

Fra: "Vitezslav Kot" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 16:00:50 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



I switched to Boost Beast library. It is better designed, much more powerful (WebSockets support) and just works. Of course I had to rewrite my request handlers, but it wasn't a big deal. 

Cpp-netlib is a great library and was indispensable before the Boot Beast release which made it obsolete.

**Comment by vitakot** [comment]
Europe, Czech Republic, Brno city.

**Comment by oddvardm** [comment]
Stavanger Norway. Glad to meet you. 


----- Opprinnelig melding -----

Fra: "Vitezslav Kot" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 16:14:23 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



Europe, Czech Republic, Brno city.

**Comment by oddvardm** [comment]
Hei, 

You there? 

O. 


----- Opprinnelig melding -----

Fra: oddvardm@getmail.no 
Til: "cpp-netlib/cpp-netlib" <reply@reply.github.com> 
Kopi: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 16:40:40 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 

Stavanger Norway. Glad to meet you. 


----- Opprinnelig melding -----

Fra: "Vitezslav Kot" <notifications@github.com> 
Til: "cpp-netlib/cpp-netlib" <cpp-netlib@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Comment" <comment@noreply.github.com> 
Sendt: 11. oktober 2019 16:14:23 
Emne: Re: [cpp-netlib/cpp-netlib] Does not compile with Boost 1.70 and newer (#875) 



Europe, Czech Republic, Brno city.

**Comment by Plaristote** [comment]
Let's get back on topic: cpp-netlib still does not compile with Boost 1.72.
The header `boost/asio/stream_socket_service.hpp` has been moved or removed, resulting in compilation errors in `boost/network/protocol/stream_handler.hpp`.

**Comment by Plaristote** [comment]
Back on this issue, it turns out these modifications weren't enough. It was enough for my http server, but not for my clients.
Seems like uses of `io_service` should sometimes be replaced by `io_context`. There's at least one instance of that issue happening in `stream_handler.hpp`. I unfortunately can't probe this issue any longer for today. I'll do my best to try and fix this in the following weeks, but I'm no asio expert, so don't take my work for it.

**Comment by Legodev** [comment]
For those that want to run 0.13.0 with Boost 1.72 here is a small patch. Think there is a much nice place for the #if #else but yeah, i admit i was to lazy to actually real the includes ...

**Comment by Legodev** [comment]
For those that want to run cpp-netlib 0.13.0 with Boost >= 1.70 i have created a quick and maybe dirty  [patch](https://gist.github.com/Legodev/9c745b7ddf0f809bd990e72c8e6a2f9d) that is only tested for my use case, so be aware it might not solve your problem!
