### PR TITLE
OSX: fix OpenSSL detection for 10.11. Fixes #690

### LINKED ISSUE #690: OSX 10.11: Undefined symbols for architecture x86_64: boost::network::http::impl::ssl_delegate::ssl_delegate()
```
[100%] Linking CXX executable ../../kovri
Undefined symbols for architecture x86_64:
  "boost::network::http::impl::ssl_delegate::ssl_delegate(boost::asio::io_service&, bool, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, long)", referenced from:
      std::__1::shared_ptr<boost::network::http::impl::ssl_delegate> std::__1::shared_ptr<boost::network::http::impl::ssl_delegate>::make_shared<boost::asio::io_service&, bool&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, long&>(boost::asio::io_service&&&, bool&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, long&&&) in libkovri-client.a(http.cc.o)
  "boost::network::http::impl::ssl_delegate::~ssl_delegate()", referenced from:
      std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate, std::__1::allocator<boost::network::http::impl::ssl_delegate> >::~__shared_ptr_emplace() in libkovri-client.a(http.cc.o)
      std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate, std::__1::allocator<boost::network::http::impl::ssl_delegate> >::~__shared_ptr_emplace() in libkovri-client.a(http.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [kovri] Error 1
make[2]: *** [src/app/CMakeFiles/kovri-app.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all-options] Error 2
```

`0.13-release` 87dd5510f479107f56764dade0454bd587cb444c
`AppleClang 7.3.0.7030031`

Complete build log here: https://build.getmonero.org/builders/kovri-tests-osx-10.11/builds/0/steps/compile/logs/stdio

Note: cpp-netlib (apparently) can't find openssl on OSX 10.11 **but** `find_package(OpenSSL)` successfully finds openssl with the same version of cmake on the same system when building kovri against openssl.

### PR DESCRIPTION
**Pull request by anonimal**
This is a confirmed fix for #690 and also confirmed to work on 10.9.5 (this should work on 10.10 as well).

The problem with this fix is the assumption that the user is using homebrew. If we shouldn't enforce this requisite, I'm open to ideas for an alternate fix.

### CODE REVIEW

**Comment by glynos** [comment]
The checks that have failed are to do with a configuration problem on Travis. I don't have access to an Apple environment. @deanberris can you confirm that this can be integrated? Also, does this fix need to be applied on the master branch?

**Comment by anonimal** [comment]
What spurred my need for a fix was https://build.getmonero.org/builders/kovri-all-osx-10.11/builds/4

I can't easily provide a new fixed build report because I can't easily update our submodule to point to my branch without causing other issues. I did ssh into this machine though and confirm manually.

**Comment by anonimal** [comment]
AFAICT this will also be needed in master, I'll confirm right now.

**Comment by anonimal** [comment]
Yes, it's needed for master too.

File: CMakeLists.txt [hunk 1]
```diff
@@ -49,7 +49,15 @@ set(Boost_USE_MULTI_THREADED ON)
 find_package(Boost 1.58.0 REQUIRED COMPONENTS system thread)
 
 if (CPP-NETLIB_ENABLE_HTTPS)
-    find_package( OpenSSL )
+  if (APPLE)
+    # If we're on OS X check for Homebrew's copy of OpenSSL instead of Apple's
+    if (NOT OpenSSL_DIR)
+      execute_process (COMMAND brew --prefix openssl
```
Comment (deanberris) [inline CMakeLists.txt]: I'm not a fan of requiring homebrew just like this unconditionally on APPLE. Personally, when I build the library I provide the `OpenSSL_DIR` option myself.

I'd be open to accepting this if you make it so that we can detect whether the user has homebrew installed (something that could be checked at configuration time).

Comment (deanberris) [inline CMakeLists.txt]: I think optional homebrew applies even to before OSX 10.11.

**Comment by anonimal** [comment]
@deanberris @glynos I've pushed acb020b. Its a little biased with the Homebrew warning but it will stay out of the way. Confirmed functional/build successful on 10.11 and earlier machines.

Should I reopen this PR to master?

**Comment by deanberris** [comment]
Also, yes, please do the same to master -- that would be most appreciated.
