### ISSUE TITLE
http::ready does not compile in 0.12

### ISSUE THREAD

**Issue by dmytrobogovych** [cpp-netlib/cpp-netlib#770]
/home/user/works/sevana/pvqa-server/lib/cpp-netlib/boost/network/protocol/http/message/wrappers/ready.hpp:30: error: ‘class std::shared_future<std::basic_string<char> >’ has no member named ‘is_ready’
            wrapper_base::_message.headers_.is_ready() &&
                                                       ^

Seems the problem is usage of std::shared_future. experimental::shared_future has is_ready() method. boost::shared_future has it too. I did see one of commits in last monthes enables boost::shared_future to use. But 0.12 release does not use it.
